parameters:
  - name: functionAppName
  - name: artifactName
  - name: serviceConnectionName

steps:
  - template: ../printEnv.yml
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/src"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
  - task: AzureFunctionApp@1
    displayName: Deploy FunctionApp
    inputs:
      azureSubscription: ${{ parameters.serviceConnectionName }}
      appType: functionApp
      appName: ${{ parameters.functionAppName }}
      package: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
