name: deploy-functionapp
variables:
  - template: ../env/global.yml
  - template: ../env/dev.yml
  # - template: ../env/tst.yml
  # - template: ../env/prd.yml
trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - ../../infra/*
stages:
  - stage: Dev
    jobs:
      - deployment: Dev_Deploy
        pool:
          vmImage: "windows-latest"
        environment: ${{ variables.devEnvironmentName }}
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deploy.yml
                  parameters:
                    artifactName: ${{ variables.artifactName }}
                    serviceConnectionName: ${{ variables.devServiceConnectionName }}
                    functionAppName: ${{ variables.devFunctionAppName }}
  # - stage: Prd
  #   dependsOn: Dev
  #   jobs:
  #   - deployment: Prd_Deploy
  #     pool:
  #       vmImage: 'windows-latest'
  #     environment: ${{ variables.prdEnvironmentName }}
  #     strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #           - template: deploy.yml
  #             parameters:
  #               artifactName: ${{ variables.artifactName }}
  #               serviceConnectionName: ${{ variables.prdServiceConnectionName }}
  #               functionAppName: ${{ variables.functionAppName }}
