resource_group_name                         = "rg-funcSbTeams-ussc-dev"
app                                         = "funcSbTeams"
region                                      = "ussc"
environment                                 = "dev"
location                                    = "South Central US"
app_service_environment_name                = "ase-centralHub-ussc-dev"
app_service_environment_resource_group_name = "rg-centralHub"
subscription_id                             = "cfa014c2-6565-444f-8241-b3edd39a2a44"
